TestSwiftDynamics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path

from .views import home_view
from .views_complete import complete_view
from .views_delete import delete_view

app_name = 'todo'
urlpatterns = [
    path('', home_view, name='home'),
    path('<int:task_id>/complete/', complete_view, name='complete'),
    path('<int:task_id>/delete/', delete_view, name='delete'),
]

todo/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=256)
    is_complete = models.BooleanField(default=False)

    datetime_complete = models.DateTimeField(null=True, blank=True)
    datetime_create = models.DateTimeField(auto_now_add=True)
    datetime_update = models.DateTimeField(auto_now=True)

todo/forms.py
from django import forms


class AddTask(forms.Form):
    name = forms.CharField(label='task_name', max_length=256)

todo/views.py
from django.shortcuts import render
from .models import Task
from .forms import AddTask


def home_view(request):
    complete_task_list = Task.objects.filter(is_complete=True)
    incomplete_task_list = Task.objects.filter(is_complete=False)
    if request.method == 'POST':
        form = AddTask(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            add_task = Task(name=name)
            add_task.save()
        else:
            form = AddTask()

    return render(
        request,
        'home.html',
        {
            'complete_task_list': complete_task_list,
            'incomplete_task_list': incomplete_task_list,
        }
    )

todo/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">
  <title>To Do List</title>
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
  <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
  <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>
  <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'assets/js/respond.min.js' %}"></script>

	<![endif]-->
  {% block head %}
  {% endblock %}
</head>

<body>
<div class="main-wrapper">
  <div class="page-wrapper">
    {% block content %}
    <div class="page-content page-container" id="page-content">
      <div class="padding">
        <div class="row container d-flex justify-content-center">
          <div class="col-md-12">
            <div class="card px-3">
              <div class="card-body">
                <h4 class="card-title">To Do list</h4>
                <form action="" method="post">
                  {% csrf_token %}
                  <div class="add-items d-flex">
                    <input id="id_name" name="name" type="text" class="form-control todo-list-input" placeholder="What do you need to do today?" ><button class="add btn btn-primary font-weight-bold todo-list-add-btn" type="submit">Add</button>
                  </div>
                </form>
              <br>
                <div class="list-wrapper">
                  <span class="badge badge-warning h5">Ongoing</span>
                  <ul class="d-flex flex-column-reverse todo-list">
                    {% for task in incomplete_task_list %}
                      <li>
                        <h4>{{ task.name }} {% if not task.is_complete %}<a class="btn btn-success" href="{% url 'todo:complete' task.id %}"><i class="fa fa-check"></i> Complete</a>{% endif %} <a class="btn btn-danger" href="{% url 'todo:delete' task.id %}"><i class="fa fa-trash"></i> Delete</a></h4>
                      </li>
                    {% endfor %}
                  </ul>
                  <span class="h5 badge badge-success">Complete</span>
                  <ul class="d-flex flex-column-reverse todo-list">
                    {% for task in complete_task_list %}
                      <li>
                        <h4>{{ task.name }} <a class="btn btn-danger" href="{% url 'todo:delete' task.id %}"><i class="fa fa-trash"></i> Delete</a></h4>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
  </div>
</div>
<div class="sidebar-overlay" data-reff=""></div>
<script type="text/javascript" src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/plugins/morris/morris.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/plugins/raphael/raphael-min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/app.js' %}"></script>
</body>

</html>